Update libraries to avoid compile error
* remove glfw
* change the logic to generate cylinder model to avoid ncollide3d's error.
  ncollide does not support nested composite.

thread 'path_planner::tests::from_urdf' panicked at 'Nested composite shapes are not allowed.', /home/
ogura/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide3d-0.18.4/src/shape/compound.rs:40:17